import { Request, Response } from 'express';
import bcrypt from 'bcrypt';
import { users } from '../db/users.js';
import { DBUser } from '../types/types.js';
import { createUser } from '../services/user.js';

export const registerUser = (req: Request, res: Response) => {
  try {
    const { first, last, dob, email, password } = req.body;
    // Hash the password
    const hashedPassword = bcrypt.hashSync(password, 10);
    // Create a new user object    
    const newUser: DBUser = {
      id: '', // This will be generated by the database
      first,
      last,
      dob,
      email,
      password: hashedPassword
    };
    createUser(newUser);
  }
  catch (error) {
    res.status(500).json({
      message: 'Error registering user'
    });
  }
}

export const loginUser = (req: Request, res: Response) => {
  res.status(200).json({
    message: 'User logged in successfully'
  });
}

export const logoutUser = (req: Request, res: Response) => {
  res.status(200).json({
    message: 'User logged out successfully'
  });
}