name: Backend Pipeline

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm', cache-dependency-path: './backend/package-lock.json' }
      - run: npm ci
        working-directory: ./backend
      - run: npm run test:unit
        working-directory: ./backend

  integration-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Run integration tests
        working-directory: ./backend
        run: docker compose run --build --rm -T sut npm run test:integration

  deploy:
    if: github.event_name == 'push'
    needs: [unit-tests]
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_HOOK }}
